# Preprocessing of application columns for baseline logistic regression
- table - app_train.csv, app_valid.csv
---

Preparing data set for modeling with baseline logistic regression
- removing unnecessary columns
- basic grouping for categorical variables
- imputing missing values and creating missing flags
- creating simple bins for discrete variables if applicable
- maping binary cols to 0, 1 values

## 0. Libarries and data

In [280]:
import pandas as pd
import numpy as np

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent.parent
SRC_PATH = PROJECT_ROOT / 'src'

from eda_module import (
    plot_quantitative_distribution, plot_binary_distribution, 
    plot_binary_vs_binary, plot_quantitative_vs_binary, plot_categorical_distribution,
    plot_categorical_vs_binary
)

from preprocess_module import (
    bin_quantitative_var, fit_optbin_var, fit_quantitative_binner, transform_quantitative_binner,
    fit_capper, transform_capper, create_imputed_quantitative_features
)

In [281]:
df_train = pd.read_csv(r"..\..\data\interim\app_train.csv")
print(f"Shape of df_train: {df_train.shape}")
print(f"Unique dtypes of df_train: {df_train.dtypes.unique()}")
df_train.head(10)

Shape of df_train: (215257, 122)
Unique dtypes of df_train: [dtype('int64') dtype('O') dtype('float64')]

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,TARGET
0,285133,Cash loans,F,Y,Y,2,405000.0,1971072.0,68643.0,1800000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,191894,Cash loans,M,N,Y,0,337500.0,508495.5,38146.5,454500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0,0
2,369428,Cash loans,M,N,Y,1,112500.0,110146.5,13068.0,90000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,138717,Cash loans,F,N,Y,2,40500.0,66384.0,3519.0,45000.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0,0
4,202381,Cash loans,M,Y,N,0,225000.0,298512.0,31801.5,270000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
5,185763,Cash loans,F,N,Y,0,315000.0,417024.0,21964.5,360000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,0
6,148765,Cash loans,M,Y,Y,0,162000.0,168102.0,11362.5,148500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0
7,448028,Cash loans,F,N,Y,0,135000.0,1129500.0,33025.5,1129500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
8,428649,Cash loans,F,N,Y,0,157500.0,1260702.0,39712.5,1129500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0
9,345767,Cash loans,F,Y,N,0,180000.0,879480.0,25843.5,630000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0,0

In [282]:
df_valid = pd.read_csv(r"..\..\data\interim\app_valid.csv")
print(f"Shape of df_valid: {df_valid.shape}")
print(f"Unique dtypes of df_valid: {df_valid.dtypes.unique()}")
df_valid.head(10)

Shape of df_valid: (92254, 122)
Unique dtypes of df_valid: [dtype('int64') dtype('O') dtype('float64')]

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,TARGET
0,331034,Cash loans,F,N,Y,0,90000.0,803259.0,23616.0,670500.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0,0
1,242581,Cash loans,F,N,Y,0,270000.0,1288350.0,41692.5,1125000.0,...,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0,0
2,281583,Cash loans,F,N,Y,0,270000.0,253737.0,25227.0,229500.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
3,255865,Cash loans,F,N,Y,0,144000.0,436032.0,16564.5,360000.0,...,0,0,0,0.0,0.0,1.0,0.0,0.0,2.0,0
4,389379,Revolving loans,M,N,N,2,72000.0,225000.0,11250.0,225000.0,...,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0
5,455506,Cash loans,M,Y,Y,0,315000.0,521280.0,27423.0,450000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0,0
6,234885,Cash loans,F,Y,Y,1,54000.0,102384.0,6673.5,81000.0,...,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0,0
7,425217,Cash loans,M,Y,N,0,315000.0,545040.0,31288.5,450000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0,0
8,209875,Cash loans,F,N,Y,1,315000.0,254700.0,13567.5,225000.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
9,106521,Cash loans,F,Y,N,0,67500.0,292500.0,13014.0,292500.0,...,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0

## 1. Removing all unnecessary columns
- technical columns
- columns with one value
- columns with high number of NANs

`SK_ID_CURR` will be removed just before saving.

In [283]:
df_train1 = df_train.copy()
df_valid1 = df_valid.copy()

In [284]:
max_acceptable_nan_share = 0.50

In [285]:
credit_bureau_cols = [
    'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
    'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR'
]

building_cols = [
    'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG',
    'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG',
    'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG',
    'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 

    'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE',
    'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE',
    'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
    'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE',

    'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI',
    'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI',
    'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI',
    'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',

    'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'
]

In [286]:
cols_to_keep = ['EXT_SOURCE_1']

cols_to_remove = [
    'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',

    'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
    'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',

    'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG',
    'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG',
    'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG',
    'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 

    'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE',
    'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE',
    'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
    'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE',

    'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI',
    'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI',
    'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI',
    'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',

    'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE'
]

In [287]:
df_train1['OWN_CAR_AGE_missing'] = np.where(df_train1['OWN_CAR_AGE'].isna(), 1, 0)
df_valid1['OWN_CAR_AGE_missing'] = np.where(df_valid1['OWN_CAR_AGE'].isna(), 1, 0)

In [288]:
df_train_nans = df_train1.isna().mean().to_frame(name='nan_train').reset_index()
df_valid_nans = df_valid1.isna().mean().to_frame(name='nan_valid').reset_index()

df_nans = df_train_nans.merge(right=df_valid_nans, on='index', how='right')
df_nans[(df_nans['nan_train']>0) | (df_nans['nan_valid']>0)].head(20)

                          index  nan_train  nan_valid
8                   AMT_ANNUITY   0.000037   0.000043
9               AMT_GOODS_PRICE   0.000869   0.000986
10              NAME_TYPE_SUITE   0.004186   0.004238
20                  OWN_CAR_AGE   0.660099   0.659462
27              OCCUPATION_TYPE   0.313486   0.313385
28              CNT_FAM_MEMBERS   0.000005   0.000011
40                 EXT_SOURCE_1   0.563852   0.563715
41                 EXT_SOURCE_2   0.002156   0.002125
42                 EXT_SOURCE_3   0.198275   0.198203
43               APARTMENTS_AVG   0.506725   0.509300
44             BASEMENTAREA_AVG   0.584385   0.586966
45  YEARS_BEGINEXPLUATATION_AVG   0.487371   0.488835
46              YEARS_BUILD_AVG   0.664489   0.666117
47               COMMONAREA_AVG   0.698235   0.699861
48                ELEVATORS_AVG   0.532247   0.534622
49                ENTRANCES_AVG   0.502980   0.504672
50                FLOORSMAX_AVG   0.496941   0.499165
51                FLOORSMIN_AVG   0.678510   0.678431
52                 LANDAREA_AVG   0.592984   0.595595
53         LIVINGAPARTMENTS_AVG   0.683132   0.684523

In [289]:
high_nan_cols = list(df_nans[
    (df_nans['nan_train']>max_acceptable_nan_share) 
    | (df_nans['nan_valid']>max_acceptable_nan_share)
]['index'].values)

high_nan_cols

['OWN_CAR_AGE',
 'EXT_SOURCE_1',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE']

In [290]:
cols_to_remove = cols_to_remove + high_nan_cols
cols_to_remove = [col for col in cols_to_remove if col not in cols_to_keep]
cols_to_remove

['WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OWN_CAR_AGE',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'WALLSMATERIAL_MODE']

In [291]:
print(f"df_train1: {df_train1.shape}")
print(f"df_valid1: {df_valid1.shape}")

df_train1: (215257, 123)
df_valid1: (92254, 123)

In [292]:
df_train1 = df_train1.drop(columns=cols_to_remove)
df_valid1 = df_valid1.drop(columns=cols_to_remove)

In [293]:
print(f"df_train1: {df_train1.shape}")
print(f"df_valid1: {df_valid1.shape}")

df_train1: (215257, 68)
df_valid1: (92254, 68)

In [294]:
num_cols = list(df_train1.select_dtypes(include=['Int64', 'float64']).columns)
cat_cols = list(df_train1.select_dtypes(include=['O']).columns)
binary_cols = [col for col in df_train1.columns if df_train1[col].nunique()==2]

print(f"len(num_cols) + len(cat_cols) == df_train1.shape[1]: {(len(num_cols) + len(cat_cols)) == df_train1.shape[1]}")
print(f"Number of binary columns: {len(binary_cols)}")

len(num_cols) + len(cat_cols) == df_train1.shape[1]: True
Number of binary columns: 37

## 2. Basic grouping for categorical columns

Max number of categories withn one variable and min share of minory category:

In [295]:
max_cat_n = 4
min_cat_share = 0.05

In [296]:
df_train2 = df_train1.copy()
df_valid2 = df_valid1.copy()

In [297]:
cat_cols_to_group = [col for col in cat_cols if df_train2[col].nunique() > 4]
print(cat_cols_to_group)

['NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'ORGANIZATION_TYPE']

In [298]:
for col in cat_cols_to_group:
    print(f"Variable: {col}\n")
    
    df_train_grouped = df_train2[[col, 'TARGET']].groupby(col).agg(
            n_obs = (col, 'count'),
            target_share = ('TARGET', 'mean')
    )
    df_train_grouped['obs_share'] = round(df_train_grouped['n_obs'] / df_train2.shape[0],4)
    df_train_grouped['target_share'] = df_train_grouped['target_share'].round(4)
    print(df_train_grouped[['n_obs', 'obs_share', 'target_share']])
    print('-' * 60)

Variable: NAME_TYPE_SUITE

                  n_obs  obs_share  target_share
NAME_TYPE_SUITE
Children           2327     0.0108        0.0743
Family            28001     0.1301        0.0734
Group of people     198     0.0009        0.0859
Other_A             614     0.0029        0.0896
Other_B            1248     0.0058        0.0994
Spouse, partner    7879     0.0366        0.0787
Unaccompanied    174089     0.8087        0.0820
------------------------------------------------------------
Variable: NAME_INCOME_TYPE

                       n_obs  obs_share  target_share
NAME_INCOME_TYPE
Businessman                9     0.0000        0.0000
Commercial associate   50106     0.2328        0.0758
Maternity leave            3     0.0000        0.0000
Pensioner              38748     0.1800        0.0539
State servant          15382     0.0715        0.0589
Student                    9     0.0000        0.0000
Unemployed                16     0.0001        0.3125
Working               110984     0.5156        0.0953
------------------------------------------------------------
Variable: NAME_EDUCATION_TYPE

                                n_obs  obs_share  target_share
NAME_EDUCATION_TYPE
Academic degree                   104     0.0005        0.0096
Higher education                52254     0.2428        0.0539
Incomplete higher                7251     0.0337        0.0883
Lower secondary                  2655     0.0123        0.1100
Secondary / secondary special  152993     0.7107        0.0891
------------------------------------------------------------
Variable: NAME_FAMILY_STATUS

                       n_obs  obs_share  target_share
NAME_FAMILY_STATUS
Civil marriage         20844     0.0968        0.0994
Married               137457     0.6386        0.0753
Separated              13854     0.0644        0.0801
Single / not married   31846     0.1479        0.0996
Unknown                    1     0.0000        0.0000
Widow                  11255     0.0523        0.0592
------------------------------------------------------------
Variable: NAME_HOUSING_TYPE

                      n_obs  obs_share  target_share
NAME_HOUSING_TYPE
Co-op apartment         791     0.0037        0.0936
House / apartment    191159     0.8881        0.0780
Municipal apartment    7803     0.0362        0.0833
Office apartment       1817     0.0084        0.0677
Rented apartment       3357     0.0156        0.1245
With parents          10330     0.0480        0.1162
------------------------------------------------------------
Variable: OCCUPATION_TYPE

                       n_obs  obs_share  target_share
OCCUPATION_TYPE
Accountants             6842     0.0318        0.0456
Cleaning staff          3310     0.0154        0.0961
Cooking staff           4178     0.0194        0.1053
Core staff             19345     0.0899        0.0646
Drivers                13088     0.0608        0.1112
HR staff                 373     0.0017        0.0643
High skill tech staff   7977     0.0371        0.0634
IT staff                 361     0.0017        0.0609
Laborers               38591     0.1793        0.1058
Low-skill Laborers      1480     0.0069        0.1791
Managers               14985     0.0696        0.0615
Medicine staff          6050     0.0281        0.0707
Private service staff   1851     0.0086        0.0643
Realty agents            524     0.0024        0.0782
Sales staff            22285     0.1035        0.0955
Secretaries              915     0.0043        0.0699
Security staff          4698     0.0218        0.1075
Waiters/barmen staff     924     0.0043        0.1169
------------------------------------------------------------
Variable: ORGANIZATION_TYPE

                        n_obs  obs_share  target_share
ORGANIZATION_TYPE
Advertising               289     0.0013        0.0934
Agriculture              1730     0.0080        0.1064
Bank                     1735     0.0081        0.0536
Business Entity Type 1   4214     0.0196        0.0783
Business Entity Type 2   7374     0.0343        0.0857
Business Entity Type 3  47582     0.2210        0.0923
Cleaning                  195     0.0009        0.1231
Construction             4704     0.0219        0.1212
Culture                   269     0.0012        0.0595
Electricity               674     0.0031        0.0727
Emergency                 395     0.0018        0.0709
Government               7324     0.0340        0.0687
Hotel                     686     0.0032        0.0700
Housing                  2055     0.0095        0.0818
Industry: type 1          737     0.0034        0.1194
Industry: type 10          75     0.0003        0.0667
Industry: type 11        1888     0.0088        0.0858
Industry: type 12         258     0.0012        0.0465
Industry: type 13          46     0.0002        0.1522
Industry: type 2          326     0.0015        0.0890
Industry: type 3         2292     0.0106        0.1043
Industry: type 4          633     0.0029        0.0885
Industry: type 5          393     0.0018        0.0763
Industry: type 6           77     0.0004        0.0519
Industry: type 7          903     0.0042        0.0742
Industry: type 8           17     0.0001        0.1176
Industry: type 9         2396     0.0111        0.0684
Insurance                 415     0.0019        0.0530
Kindergarten             4891     0.0227        0.0712
Legal Services            218     0.0010        0.0963
Medicine                 7917     0.0368        0.0695
Military                 1857     0.0086        0.0501
Mobile                    211     0.0010        0.0806
Other                   11662     0.0542        0.0746
Police                   1608     0.0075        0.0522
Postal                   1520     0.0071        0.0829
Realtor                   279     0.0013        0.1147
Religion                   59     0.0003        0.0508
Restaurant               1285     0.0060        0.1160
School                   6296     0.0292        0.0583
Security                 2302     0.0107        0.1056
Security Ministries      1403     0.0065        0.0520
Self-employed           26681     0.1239        0.1024
Services                 1089     0.0051        0.0597
Telecom                   396     0.0018        0.0833
Trade: type 1             237     0.0011        0.0970
Trade: type 2            1338     0.0062        0.0658
Trade: type 3            2425     0.0113        0.1010
Trade: type 4              45     0.0002        0.0222
Trade: type 5              34     0.0002        0.0294
Trade: type 6             425     0.0020        0.0400
Trade: type 7            5450     0.0253        0.0939
Transport: type 1         145     0.0007        0.0552
Transport: type 2        1529     0.0071        0.0726
Transport: type 3         851     0.0040        0.1586
Transport: type 4        3749     0.0174        0.0891
University                917     0.0043        0.0523
XNA                     38756     0.1800        0.0541
------------------------------------------------------------

In [299]:
categories_to_group = {}
special_grouping_cols = []

for col in cat_cols_to_group:
    print(f"Variable: {col}")
    
    df_train_grouped = df_train2[[col, 'TARGET']].groupby(col).agg(
            n_obs = (col, 'count'),
            target_share = ('TARGET', 'mean')
    )
    df_train_grouped['obs_share'] = round(df_train_grouped['n_obs'] / df_train2.shape[0],4)
    df_train_grouped['target_share'] = df_train_grouped['target_share'].round(4)

    minor_cat_share = df_train_grouped[
        df_train_grouped['obs_share'] < 0.05
    ]['obs_share'].sum()

    categories_to_group[col] = list(df_train_grouped[df_train_grouped['obs_share']< 0.05].index)
    
    if minor_cat_share < 0.05:
        min_acceptable_share = df_train_grouped[df_train_grouped['obs_share']>=0.05]['obs_share'].min()
        other_canidadate = df_train_grouped[df_train_grouped['obs_share']==min_acceptable_share].index[0]
        categories_to_group[col].append(other_canidadate)
        special_grouping_cols.append(col)


    print(f"Share of minor categories: {minor_cat_share}\n")
    print(df_train_grouped[df_train_grouped['obs_share']< 0.05][['n_obs', 'obs_share', 'target_share']])
    print('-' * 60)

Variable: NAME_TYPE_SUITE
Share of minor categories: 0.057

                 n_obs  obs_share  target_share
NAME_TYPE_SUITE
Children          2327     0.0108        0.0743
Group of people    198     0.0009        0.0859
Other_A            614     0.0029        0.0896
Other_B           1248     0.0058        0.0994
Spouse, partner   7879     0.0366        0.0787
------------------------------------------------------------
Variable: NAME_INCOME_TYPE
Share of minor categories: 0.0001

                  n_obs  obs_share  target_share
NAME_INCOME_TYPE
Businessman           9     0.0000        0.0000
Maternity leave       3     0.0000        0.0000
Student               9     0.0000        0.0000
Unemployed           16     0.0001        0.3125
------------------------------------------------------------
Variable: NAME_EDUCATION_TYPE
Share of minor categories: 0.0465

                     n_obs  obs_share  target_share
NAME_EDUCATION_TYPE
Academic degree        104     0.0005        0.0096
Incomplete higher     7251     0.0337        0.0883
Lower secondary       2655     0.0123        0.1100
------------------------------------------------------------
Variable: NAME_FAMILY_STATUS
Share of minor categories: 0.0

                    n_obs  obs_share  target_share
NAME_FAMILY_STATUS
Unknown                 1        0.0           0.0
------------------------------------------------------------
Variable: NAME_HOUSING_TYPE
Share of minor categories: 0.1119

                     n_obs  obs_share  target_share
NAME_HOUSING_TYPE
Co-op apartment        791     0.0037        0.0936
Municipal apartment   7803     0.0362        0.0833
Office apartment      1817     0.0084        0.0677
Rented apartment      3357     0.0156        0.1245
With parents         10330     0.0480        0.1162
------------------------------------------------------------
Variable: OCCUPATION_TYPE
Share of minor categories: 0.18350000000000002

                       n_obs  obs_share  target_share
OCCUPATION_TYPE
Accountants             6842     0.0318        0.0456
Cleaning staff          3310     0.0154        0.0961
Cooking staff           4178     0.0194        0.1053
HR staff                 373     0.0017        0.0643
High skill tech staff   7977     0.0371        0.0634
IT staff                 361     0.0017        0.0609
Low-skill Laborers      1480     0.0069        0.1791
Medicine staff          6050     0.0281        0.0707
Private service staff   1851     0.0086        0.0643
Realty agents            524     0.0024        0.0782
Secretaries              915     0.0043        0.0699
Security staff          4698     0.0218        0.1075
Waiters/barmen staff     924     0.0043        0.1169
------------------------------------------------------------
Variable: ORGANIZATION_TYPE
Share of minor categories: 0.4207

                        n_obs  obs_share  target_share
ORGANIZATION_TYPE
Advertising               289     0.0013        0.0934
Agriculture              1730     0.0080        0.1064
Bank                     1735     0.0081        0.0536
Business Entity Type 1   4214     0.0196        0.0783
Business Entity Type 2   7374     0.0343        0.0857
Cleaning                  195     0.0009        0.1231
Construction             4704     0.0219        0.1212
Culture                   269     0.0012        0.0595
Electricity               674     0.0031        0.0727
Emergency                 395     0.0018        0.0709
Government               7324     0.0340        0.0687
Hotel                     686     0.0032        0.0700
Housing                  2055     0.0095        0.0818
Industry: type 1          737     0.0034        0.1194
Industry: type 10          75     0.0003        0.0667
Industry: type 11        1888     0.0088        0.0858
Industry: type 12         258     0.0012        0.0465
Industry: type 13          46     0.0002        0.1522
Industry: type 2          326     0.0015        0.0890
Industry: type 3         2292     0.0106        0.1043
Industry: type 4          633     0.0029        0.0885
Industry: type 5          393     0.0018        0.0763
Industry: type 6           77     0.0004        0.0519
Industry: type 7          903     0.0042        0.0742
Industry: type 8           17     0.0001        0.1176
Industry: type 9         2396     0.0111        0.0684
Insurance                 415     0.0019        0.0530
Kindergarten             4891     0.0227        0.0712
Legal Services            218     0.0010        0.0963
Medicine                 7917     0.0368        0.0695
Military                 1857     0.0086        0.0501
Mobile                    211     0.0010        0.0806
Police                   1608     0.0075        0.0522
Postal                   1520     0.0071        0.0829
Realtor                   279     0.0013        0.1147
Religion                   59     0.0003        0.0508
Restaurant               1285     0.0060        0.1160
School                   6296     0.0292        0.0583
Security                 2302     0.0107        0.1056
Security Ministries      1403     0.0065        0.0520
Services                 1089     0.0051        0.0597
Telecom                   396     0.0018        0.0833
Trade: type 1             237     0.0011        0.0970
Trade: type 2            1338     0.0062        0.0658
Trade: type 3            2425     0.0113        0.1010
Trade: type 4              45     0.0002        0.0222
Trade: type 5              34     0.0002        0.0294
Trade: type 6             425     0.0020        0.0400
Trade: type 7            5450     0.0253        0.0939
Transport: type 1         145     0.0007        0.0552
Transport: type 2        1529     0.0071        0.0726
Transport: type 3         851     0.0040        0.1586
Transport: type 4        3749     0.0174        0.0891
University                917     0.0043        0.0523
------------------------------------------------------------

In [300]:
print(categories_to_group)
print(len(categories_to_group))

{'NAME_TYPE_SUITE': ['Children', 'Group of people', 'Other_A', 'Other_B', 'Spouse, partner'], 'NAME_INCOME_TYPE': ['Businessman', 'Maternity leave', 'Student', 'Unemployed', 'State servant'], 'NAME_EDUCATION_TYPE': ['Academic degree', 'Incomplete higher', 'Lower secondary', 'Higher education'], 'NAME_FAMILY_STATUS': ['Unknown', 'Widow'], 'NAME_HOUSING_TYPE': ['Co-op apartment', 'Municipal apartment', 'Office apartment', 'Rented apartment', 'With parents'], 'OCCUPATION_TYPE': ['Accountants', 'Cleaning staff', 'Cooking staff', 'HR staff', 'High skill tech staff', 'IT staff', 'Low-skill Laborers', 'Medicine staff', 'Private service staff', 'Realty agents', 'Secretaries', 'Security staff', 'Waiters/barmen staff'], 'ORGANIZATION_TYPE': ['Advertising', 'Agriculture', 'Bank', 'Business Entity Type 1', 'Business Entity Type 2', 'Cleaning', 'Construction', 'Culture', 'Electricity', 'Emergency', 'Government', 'Hotel', 'Housing', 'Industry: type 1', 'Industry: type 10', 'Industry: type 11', 'Industry: type 12', 'Industry: type 13', 'Industry: type 2', 'Industry: type 3', 'Industry: type 4', 'Industry: type 5', 'Industry: type 6', 'Industry: type 7', 'Industry: type 8', 'Industry: type 9', 'Insurance', 'Kindergarten', 'Legal Services', 'Medicine', 'Military', 'Mobile', 'Police', 'Postal', 'Realtor', 'Religion', 'Restaurant', 'School', 'Security', 'Security Ministries', 'Services', 'Telecom', 'Trade: type 1', 'Trade: type 2', 'Trade: type 3', 'Trade: type 4', 'Trade: type 5', 'Trade: type 6', 'Trade: type 7', 'Transport: type 1', 'Transport: type 2', 'Transport: type 3', 'Transport: type 4', 'University']}
7

In [301]:
print(special_grouping_cols)
print(len(special_grouping_cols))

['NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS']
3

### 2.1 Grouping all minor categories into 'other'

In [302]:
df_train2_1 = df_train2.copy()
for col in categories_to_group.keys():
    if col not in special_grouping_cols:
        df_train2_1[col] = np.where(
            df_train2_1[col].isin(categories_to_group[col]),
            'other',
            df_train2_1[col]
        )

In [303]:
for col in cat_cols_to_group:
    print(f"Variable: {col}")
    print(df_train[col].value_counts() / df_train.shape[0])
    print("-"*60)

Variable: NAME_TYPE_SUITE
NAME_TYPE_SUITE
Unaccompanied      0.808750
Family             0.130082
Spouse, partner    0.036603
Children           0.010810
Other_B            0.005798
Other_A            0.002852
Group of people    0.000920
Name: count, dtype: float64
------------------------------------------------------------
Variable: NAME_INCOME_TYPE
NAME_INCOME_TYPE
Working                 0.515588
Commercial associate    0.232773
Pensioner               0.180008
State servant           0.071459
Unemployed              0.000074
Student                 0.000042
Businessman             0.000042
Maternity leave         0.000014
Name: count, dtype: float64
------------------------------------------------------------
Variable: NAME_EDUCATION_TYPE
NAME_EDUCATION_TYPE
Secondary / secondary special    0.710746
Higher education                 0.242752
Incomplete higher                0.033685
Lower secondary                  0.012334
Academic degree                  0.000483
Name: count, dtype: float64
------------------------------------------------------------
Variable: NAME_FAMILY_STATUS
NAME_FAMILY_STATUS
Married                 0.638572
Single / not married    0.147944
Civil marriage          0.096833
Separated               0.064360
Widow                   0.052286
Unknown                 0.000005
Name: count, dtype: float64
------------------------------------------------------------
Variable: NAME_HOUSING_TYPE
NAME_HOUSING_TYPE
House / apartment      0.888050
With parents           0.047989
Municipal apartment    0.036250
Rented apartment       0.015595
Office apartment       0.008441
Co-op apartment        0.003675
Name: count, dtype: float64
------------------------------------------------------------
Variable: OCCUPATION_TYPE
OCCUPATION_TYPE
Laborers                 0.179279
Sales staff              0.103527
Core staff               0.089869
Managers                 0.069614
Drivers                  0.060802
High skill tech staff    0.037058
Accountants              0.031785
Medicine staff           0.028106
Security staff           0.021825
Cooking staff            0.019409
Cleaning staff           0.015377
Private service staff    0.008599
Low-skill Laborers       0.006876
Waiters/barmen staff     0.004293
Secretaries              0.004251
Realty agents            0.002434
HR staff                 0.001733
IT staff                 0.001677
Name: count, dtype: float64
------------------------------------------------------------
Variable: ORGANIZATION_TYPE
ORGANIZATION_TYPE
Business Entity Type 3    0.221047
XNA                       0.180045
Self-employed             0.123950
Other                     0.054177
Medicine                  0.036779
Business Entity Type 2    0.034257
Government                0.034024
School                    0.029249
Trade: type 7             0.025319
Kindergarten              0.022722
Construction              0.021853
Business Entity Type 1    0.019577
Transport: type 4         0.017416
Trade: type 3             0.011266
Industry: type 9          0.011131
Security                  0.010694
Industry: type 3          0.010648
Housing                   0.009547
Industry: type 11         0.008771
Military                  0.008627
Bank                      0.008060
Agriculture               0.008037
Police                    0.007470
Transport: type 2         0.007103
Postal                    0.007061
Security Ministries       0.006518
Trade: type 2             0.006216
Restaurant                0.005970
Services                  0.005059
University                0.004260
Industry: type 7          0.004195
Transport: type 3         0.003953
Industry: type 1          0.003424
Hotel                     0.003187
Electricity               0.003131
Industry: type 4          0.002941
Trade: type 6             0.001974
Insurance                 0.001928
Telecom                   0.001840
Emergency                 0.001835
Industry: type 5          0.001826
Industry: type 2          0.001514
Advertising               0.001343
Realtor                   0.001296
Culture                   0.001250
Industry: type 12         0.001199
Trade: type 1             0.001101
Legal Services            0.001013
Mobile                    0.000980
Cleaning                  0.000906
Transport: type 1         0.000674
Industry: type 6          0.000358
Industry: type 10         0.000348
Religion                  0.000274
Industry: type 13         0.000214
Trade: type 4             0.000209
Trade: type 5             0.000158
Industry: type 8          0.000079
Name: count, dtype: float64
------------------------------------------------------------

In [304]:
for col in cat_cols_to_group:
    print(f"Variable: {col}")
    print(df_train[col].value_counts())
    print("-"*60)

Variable: NAME_TYPE_SUITE
NAME_TYPE_SUITE
Unaccompanied      174089
Family              28001
Spouse, partner      7879
Children             2327
Other_B              1248
Other_A               614
Group of people       198
Name: count, dtype: int64
------------------------------------------------------------
Variable: NAME_INCOME_TYPE
NAME_INCOME_TYPE
Working                 110984
Commercial associate     50106
Pensioner                38748
State servant            15382
Unemployed                  16
Student                      9
Businessman                  9
Maternity leave              3
Name: count, dtype: int64
------------------------------------------------------------
Variable: NAME_EDUCATION_TYPE
NAME_EDUCATION_TYPE
Secondary / secondary special    152993
Higher education                  52254
Incomplete higher                  7251
Lower secondary                    2655
Academic degree                     104
Name: count, dtype: int64
------------------------------------------------------------
Variable: NAME_FAMILY_STATUS
NAME_FAMILY_STATUS
Married                 137457
Single / not married     31846
Civil marriage           20844
Separated                13854
Widow                    11255
Unknown                      1
Name: count, dtype: int64
------------------------------------------------------------
Variable: NAME_HOUSING_TYPE
NAME_HOUSING_TYPE
House / apartment      191159
With parents            10330
Municipal apartment      7803
Rented apartment         3357
Office apartment         1817
Co-op apartment           791
Name: count, dtype: int64
------------------------------------------------------------
Variable: OCCUPATION_TYPE
OCCUPATION_TYPE
Laborers                 38591
Sales staff              22285
Core staff               19345
Managers                 14985
Drivers                  13088
High skill tech staff     7977
Accountants               6842
Medicine staff            6050
Security staff            4698
Cooking staff             4178
Cleaning staff            3310
Private service staff     1851
Low-skill Laborers        1480
Waiters/barmen staff       924
Secretaries                915
Realty agents              524
HR staff                   373
IT staff                   361
Name: count, dtype: int64
------------------------------------------------------------
Variable: ORGANIZATION_TYPE
ORGANIZATION_TYPE
Business Entity Type 3    47582
XNA                       38756
Self-employed             26681
Other                     11662
Medicine                   7917
Business Entity Type 2     7374
Government                 7324
School                     6296
Trade: type 7              5450
Kindergarten               4891
Construction               4704
Business Entity Type 1     4214
Transport: type 4          3749
Trade: type 3              2425
Industry: type 9           2396
Security                   2302
Industry: type 3           2292
Housing                    2055
Industry: type 11          1888
Military                   1857
Bank                       1735
Agriculture                1730
Police                     1608
Transport: type 2          1529
Postal                     1520
Security Ministries        1403
Trade: type 2              1338
Restaurant                 1285
Services                   1089
University                  917
Industry: type 7            903
Transport: type 3           851
Industry: type 1            737
Hotel                       686
Electricity                 674
Industry: type 4            633
Trade: type 6               425
Insurance                   415
Telecom                     396
Emergency                   395
Industry: type 5            393
Industry: type 2            326
Advertising                 289
Realtor                     279
Culture                     269
Industry: type 12           258
Trade: type 1               237
Legal Services              218
Mobile                      211
Cleaning                    195
Transport: type 1           145
Industry: type 6             77
Industry: type 10            75
Religion                     59
Industry: type 13            46
Trade: type 4                45
Trade: type 5                34
Industry: type 8             17
Name: count, dtype: int64
------------------------------------------------------------

### 2.2 Handling special grouping strategies

In [305]:
df_train2_2 = df_train2_1.copy()

In [306]:
print(special_grouping_cols)

['NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS']

In [307]:
for col in special_grouping_cols:
    df_train_grouped = df_train2_2[[col, 'TARGET']].groupby(col).agg(
            n_obs = (col, 'count'),
            target_share = ('TARGET', 'mean')
    )
    df_train_grouped['obs_share'] = round(df_train_grouped['n_obs'] / df_train.shape[0],4)
    df_train_grouped['target_share'] = df_train_grouped['target_share'].round(4)

    print(f"Variable: {col}")
    print(df_train_grouped[['n_obs', 'obs_share', 'target_share']])
    print('-'*50, '\n')

Variable: NAME_INCOME_TYPE
                       n_obs  obs_share  target_share
NAME_INCOME_TYPE
Businessman                9     0.0000        0.0000
Commercial associate   50106     0.2328        0.0758
Maternity leave            3     0.0000        0.0000
Pensioner              38748     0.1800        0.0539
State servant          15382     0.0715        0.0589
Student                    9     0.0000        0.0000
Unemployed                16     0.0001        0.3125
Working               110984     0.5156        0.0953
--------------------------------------------------

Variable: NAME_EDUCATION_TYPE
                                n_obs  obs_share  target_share
NAME_EDUCATION_TYPE
Academic degree                   104     0.0005        0.0096
Higher education                52254     0.2428        0.0539
Incomplete higher                7251     0.0337        0.0883
Lower secondary                  2655     0.0123        0.1100
Secondary / secondary special  152993     0.7107        0.0891
--------------------------------------------------

Variable: NAME_FAMILY_STATUS
                       n_obs  obs_share  target_share
NAME_FAMILY_STATUS
Civil marriage         20844     0.0968        0.0994
Married               137457     0.6386        0.0753
Separated              13854     0.0644        0.0801
Single / not married   31846     0.1479        0.0996
Unknown                    1     0.0000        0.0000
Widow                  11255     0.0523        0.0592
--------------------------------------------------

In [308]:
df_train2_2['NAME_INCOME_TYPE'] = np.where(
    df_train2_2['NAME_INCOME_TYPE'].isin(categories_to_group['NAME_INCOME_TYPE'] + ['State servant']),
    'State_servant',
    df_train2_2['NAME_INCOME_TYPE']
)

df_train2_2['NAME_INCOME_TYPE'].value_counts() / df_train2_2.shape[0]

NAME_INCOME_TYPE
Working                 0.515588
Commercial associate    0.232773
Pensioner               0.180008
State_servant           0.071631
Name: count, dtype: float64

In [309]:
df_train2_2['NAME_EDUCATION_TYPE'] = np.where(
    df_train2_2['NAME_EDUCATION_TYPE'].isin(['Academic degree', 'Higher education']),
    'Higher / Academic degree',
    'Secondary / Incomplete higher'
)

df_train2_2['NAME_EDUCATION_TYPE'].value_counts() / df_train2_2.shape[0]

NAME_EDUCATION_TYPE
Secondary / Incomplete higher    0.756765
Higher / Academic degree         0.243235
Name: count, dtype: float64

In [310]:
df_train2_2['edu_higher_academic'] = np.where(
    df_train2_2['NAME_EDUCATION_TYPE'] == 'Higher / Academic degree', 1, 0
)

df_train2_2['edu_secondary_incomp_higher'] = np.where(
    df_train2_2['NAME_EDUCATION_TYPE'] == 'Secondary / Incomplete higher', 1, 0
)

df_train2_2 = df_train2_2.drop(columns=['NAME_EDUCATION_TYPE'])

In [311]:
df_train2_2['NAME_FAMILY_STATUS'] = np.where(
    df_train2_2['NAME_FAMILY_STATUS'].isin(['Civil marriage', 'Single / not married']),
    'Civil marriage / Single / not married',
    np.where(
        df_train2_2['NAME_FAMILY_STATUS'].isin(['Married', 'Unknown']),
        'Married',
        df_train2_2['NAME_FAMILY_STATUS']
    )
)

df_train2_2['NAME_FAMILY_STATUS'].value_counts() / df_train2_2.shape[0]

NAME_FAMILY_STATUS
Married                                  0.638576
Civil marriage / Single / not married    0.244777
Separated                                0.064360
Widow                                    0.052286
Name: count, dtype: float64

In [312]:
df_train2_2

,SK_ID_CURR,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_YEAR,TARGET,OWN_CAR_AGE_missing,edu_higher_academic,edu_secondary_incomp_higher
0,285133,Cash loans,F,Y,Y,2,405000.0,1971072.0,68643.0,1800000.0,...,0,0,0,0,0,0.0,0,0,1,0
1,191894,Cash loans,M,N,Y,0,337500.0,508495.5,38146.5,454500.0,...,0,0,0,0,0,6.0,0,1,1,0
2,369428,Cash loans,M,N,Y,1,112500.0,110146.5,13068.0,90000.0,...,0,0,0,0,0,NaN,0,1,0,1
3,138717,Cash loans,F,N,Y,2,40500.0,66384.0,3519.0,45000.0,...,0,0,0,0,0,2.0,0,1,0,1
4,202381,Cash loans,M,Y,N,0,225000.0,298512.0,31801.5,270000.0,...,0,0,0,0,0,0.0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,297241,Cash loans,F,N,Y,1,157500.0,846517.5,33700.5,684000.0,...,0,0,0,0,0,4.0,0,1,1,0
215253,136325,Revolving loans,F,N,Y,1,135000.0,405000.0,20250.0,405000.0,...,0,0,0,0,0,NaN,0,1,0,1
215254,240509,Cash loans,F,N,N,0,157500.0,272520.0,21528.0,225000.0,...,0,0,0,0,0,4.0,0,1,0,1
215255,387513,Cash loans,F,N,N,0,90000.0,246357.0,24493.5,234000.0,...,0,0,0,0,0,1.0,0,1,0,1
215256,449767,Revolving loans,M,Y,Y,1,225000.0,270000.0,13500.0,270000.0,...,0,0,0,0,0,2.0,1,0,1,0